### ISSUE TITLE
Cluster map for Seoul campus

### ISSUE THREAD

**Issue by cos18** [femaury/intra_42#4]
Thanks for making this wonderful app. I'm cadet from Seoul and recently Seoul open cluster, and I knew that there are map in the app. Can you make maps for my campus?

Here are map images.
<img width="661" alt="스크린샷 2020-07-03 오전 11 17 55" src="https://user-images.githubusercontent.com/33975709/86425087-2fb13580-bd1f-11ea-8466-e76a07ebe210.png">
<img width="698" alt="스크린샷 2020-07-03 오전 11 18 01" src="https://user-images.githubusercontent.com/33975709/86425091-317af900-bd1f-11ea-8c8f-071733fd1177.png">
<img width="650" alt="스크린샷 2020-07-03 오전 11 18 06" src="https://user-images.githubusercontent.com/33975709/86425095-32ac2600-bd1f-11ea-8776-77cc759b543a.png">
<img width="682" alt="스크린샷 2020-07-03 오전 11 18 10" src="https://user-images.githubusercontent.com/33975709/86425097-33dd5300-bd1f-11ea-841a-e009cee6eb1e.png">
<img width="645" alt="스크린샷 2020-07-03 오전 11 18 16" src="https://user-images.githubusercontent.com/33975709/86425099-350e8000-bd1f-11ea-9bc7-cc7148095e71.png">
<img width="679" alt="스크린샷 2020-07-03 오전 11 18 22" src="https://user-images.githubusercontent.com/33975709/86425104-36d84380-bd1f-11ea-93cc-45371916d7b4.png">

There are 6 areas. c1, 2 are in 2nd floor, c3, 4 are in 4th floor, c5, 6 are in 5th floor.

**Comment by femaury** [comment]
Hey! Thank you for the kind words 😁

And yes, of course! Thanks for the screenshots. As soon as I get some time I will add the Seoul cluster maps.

**Comment by femaury** [comment]
@cos18 Just one quick question because sometimes the maps on the intra are not 100% accurate... Do c1r5p2, c1r5p4, c3r5p2, c3r5p4, c5r5p2 and c5r5p4 exist or not? If not what is there instead (empty space, wall, etc...)?

**Comment by cos18** [comment]
@femaury I think it's intra error. There exist Macs. And in Seoul, seat number are named cXrXsX style.

**Comment by femaury** [comment]
Added in v2.1.2 (98d35989658448e64a2c76e570bbbe7a13dc5ffc)! It is currently awaiting Apple approval to be released on the App Store!
